---
version: "3.1"
services:
  lw-nginx:
    container_name: lw-dev-webserver
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/share/nginx/html
    ports:
      - 8080:80
  
    restart: unless-stopped